name = "crosant"
main = "src/app/api/hello/route.js"
compatibility_date = "2023-10-10"

[[d1_databases]]
binding = "DB" 
database_name = "crosantdb"
database_id = "1e15faddd0ea4836af865f828e67711c"


