
import './globals.css'

import { Inter } from 'next/font/google'
import SideNav from './component/SideNav'

const inter = Inter({ 
  weight: ['400', '900'],
  subsets: ['latin'], })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html  className="  h-screen  w-screen"lang="en">
      <body className={inter.className}>
          <SideNav/> 

            {children}
        </body>
    </html>
  )
}
